changelog:
  categories:
    - title: Features
      labels:
        - feature
    - title: Bug Fixes
      labels:
        - fix
    - title: Refactor
      labels:
        - refactor
    - title: Maintenance
      labels:
        - chore
    - title: Other Changes
      labels:
        - "*"
